import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Canvas from "../../components/Canvas";
import styles from "../../styles/Game.module.scss";

const Home: NextPage = () => {
  const canvasRef = React.useRef<HTMLDivElement>(null!);
  
  return (
    <div>
      <Head>
        <title>Игра</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.game}>
        <div className={styles.chat}>
          <div className={styles.chatTitle}>Чат</div>
          <div className={styles.chatMessages}>
            <div className={styles.chatItem}>
              <b>Vasya</b>
              <p>Hello world!!!</p>
            </div>
          </div>
          <div className={styles.chatInput}>
            <input type="text" />
            <button>Отправить</button>
          </div>
        </div>

        <div ref={canvasRef} className={styles.canvas}>
          <Canvas
            width={canvasRef.current?.offsetWidth}
            height={canvasRef.current?.offsetHeight}
          />
        </div>
      </div>
    </div>
  );
};

export default Home;
